In [1]:
#libraries for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("../data/raw/patient_encounters_2023.csv")

In [3]:
#shape
df.shape

(101766, 50)

In [4]:
#columns
df.columns
cols = df.columns.tolist()

for col in cols:
    print(col)

encounter_id
patient_nbr
race
gender
age
weight
admission_type_id
discharge_disposition_id
admission_source_id
time_in_hospital
payer_code
medical_specialty
num_lab_procedures
num_procedures
num_medications
number_outpatient
number_emergency
number_inpatient
diag_1
diag_2
diag_3
number_diagnoses
max_glu_serum
A1Cresult
metformin
repaglinide
nateglinide
chlorpropamide
glimepiride
acetohexamide
glipizide
glyburide
tolbutamide
pioglitazone
rosiglitazone
acarbose
miglitol
troglitazone
tolazamide
examide
citoglipton
insulin
glyburide-metformin
glipizide-metformin
glimepiride-pioglitazone
metformin-rosiglitazone
metformin-pioglitazone
change
diabetesMed
readmitted


In [5]:
#dtypes for each column
df.dtypes

encounter_id                int64
patient_nbr                 int64
race                          str
gender                        str
age                           str
weight                        str
admission_type_id           int64
discharge_disposition_id    int64
admission_source_id         int64
time_in_hospital            int64
payer_code                    str
medical_specialty             str
num_lab_procedures          int64
num_procedures              int64
num_medications             int64
number_outpatient           int64
number_emergency            int64
number_inpatient            int64
diag_1                        str
diag_2                        str
diag_3                        str
number_diagnoses            int64
max_glu_serum                 str
A1Cresult                     str
metformin                     str
repaglinide                   str
nateglinide                   str
chlorpropamide                str
glimepiride                   str
acetohexamide 

In [6]:
#all null values
df.replace(["?", "NA", "N/A", "null", "None", ""], np.nan, inplace=True)

df.isnull().sum()


encounter_id                    0
patient_nbr                     0
race                         2273
gender                          0
age                             0
weight                      98569
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  40256
medical_specialty           49949
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                         21
diag_2                        358
diag_3                       1423
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide 

In [7]:
#other nulls
fake_nulls = ["?", "NA", "N/A", "null", "None", ""]

for col in df.columns:
    print(f"\nColumn: {col}")
    print(df[col].isin(fake_nulls).sum())


Column: encounter_id
0

Column: patient_nbr
0

Column: race
0

Column: gender
0

Column: age
0

Column: weight
0

Column: admission_type_id
0

Column: discharge_disposition_id
0

Column: admission_source_id
0

Column: time_in_hospital
0

Column: payer_code
0

Column: medical_specialty
0

Column: num_lab_procedures
0

Column: num_procedures
0

Column: num_medications
0

Column: number_outpatient
0

Column: number_emergency
0

Column: number_inpatient
0

Column: diag_1
0

Column: diag_2
0

Column: diag_3
0

Column: number_diagnoses
0

Column: max_glu_serum
0

Column: A1Cresult
0

Column: metformin
0

Column: repaglinide
0

Column: nateglinide
0

Column: chlorpropamide
0

Column: glimepiride
0

Column: acetohexamide
0

Column: glipizide
0

Column: glyburide
0

Column: tolbutamide
0

Column: pioglitazone
0

Column: rosiglitazone
0

Column: acarbose
0

Column: miglitol
0

Column: troglitazone
0

Column: tolazamide
0

Column: examide
0

Column: citoglipton
0

Column: insulin
0

Column: glyb

In [8]:
#empty strings/spaces
for col in df.select_dtypes(include='object'):
    print(f"\nColumn: {col}")
    print((df[col].str.strip() == "").sum())


Column: race
0

Column: gender
0

Column: age
0

Column: weight
0

Column: payer_code


C:\Users\altre\AppData\Local\Temp\ipykernel_47752\310367471.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object'):


0

Column: medical_specialty
0

Column: diag_1
0

Column: diag_2
0

Column: diag_3
0

Column: max_glu_serum
0

Column: A1Cresult
0

Column: metformin
0

Column: repaglinide
0

Column: nateglinide
0

Column: chlorpropamide
0

Column: glimepiride
0

Column: acetohexamide
0

Column: glipizide
0

Column: glyburide
0

Column: tolbutamide
0

Column: pioglitazone
0

Column: rosiglitazone
0

Column: acarbose
0

Column: miglitol
0

Column: troglitazone
0

Column: tolazamide
0

Column: examide
0

Column: citoglipton
0

Column: insulin
0

Column: glyburide-metformin
0

Column: glipizide-metformin
0

Column: glimepiride-pioglitazone
0

Column: metformin-rosiglitazone
0

Column: metformin-pioglitazone
0

Column: change
0

Column: diabetesMed
0

Column: readmitted
0


In [9]:
#unique values
for col in df.columns:
    print(f"\n{col}")
    print(df[col].unique()[:10]) 


encounter_id
[2278392  149190   64410  500364   16680   35754   55842   63768   12522
   15738]

patient_nbr
[  8222157  55629189  86047875  82442376  42519267  82637451  84259809
 114882984  48330783  63555939]

race
<StringArray>
['Caucasian', 'AfricanAmerican', nan, 'Other', 'Asian', 'Hispanic']
Length: 6, dtype: str

gender
<StringArray>
['Female', 'Male', 'Unknown/Invalid']
Length: 3, dtype: str

age
<StringArray>
[  '[0-10)',  '[10-20)',  '[20-30)',  '[30-40)',  '[40-50)',  '[50-60)',
  '[60-70)',  '[70-80)',  '[80-90)', '[90-100)']
Length: 10, dtype: str

weight
<StringArray>
[        nan,  '[75-100)',   '[50-75)',    '[0-25)', '[100-125)',   '[25-50)',
 '[125-150)', '[175-200)', '[150-175)',      '>200']
Length: 10, dtype: str

admission_type_id
[6 1 2 3 4 5 8 7]

discharge_disposition_id
[25  1  3  6  2  5 11  7 10  4]

admission_source_id
[ 1  7  2  4  5  6 20  3 17  8]

time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10]

payer_code
<StringArray>
[nan, 'MC', 'MD', 'HM', 'UN', 

In [10]:
#Value Counts (Best for catching hidden issues)
for col in df.columns:
    print(f"\n===== {col} =====")
    print(df[col].value_counts(dropna=False))


===== encounter_id =====
encounter_id
2278392      1
149190       1
64410        1
500364       1
16680        1
            ..
443847548    1
443847782    1
443854148    1
443857166    1
443867222    1
Name: count, Length: 101766, dtype: int64

===== patient_nbr =====
patient_nbr
88785891     40
43140906     28
1660293      23
23199021     23
88227540     23
             ..
183087545     1
188574944     1
140199494     1
120975314     1
175429310     1
Name: count, Length: 71518, dtype: int64

===== race =====
race
Caucasian          76099
AfricanAmerican    19210
NaN                 2273
Hispanic            2037
Other               1506
Asian                641
Name: count, dtype: int64

===== gender =====
gender
Female             54708
Male               47055
Unknown/Invalid        3
Name: count, dtype: int64

===== age =====
age
[70-80)     26068
[60-70)     22483
[50-60)     17256
[80-90)     17197
[40-50)      9685
[30-40)      3775
[90-100)     2793
[20-30)      1657
[10-20) 

In [11]:
#Detect Strings That Should Be Numeric
for col in df.columns:
    if df[col].dtype == 'object':
        try:
            pd.to_numeric(df[col])
        except:
            print(f"{col} may contain non-numeric or dirty values")

In [12]:
#target variable distribution/class imbalance
for col in df.columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(normalize=True) * 100)


Column: encounter_id
encounter_id
2278392      0.000983
149190       0.000983
64410        0.000983
500364       0.000983
16680        0.000983
               ...   
443847548    0.000983
443847782    0.000983
443854148    0.000983
443857166    0.000983
443867222    0.000983
Name: proportion, Length: 101766, dtype: float64

Column: patient_nbr
patient_nbr
88785891     0.039306
43140906     0.027514
1660293      0.022601
23199021     0.022601
88227540     0.022601
               ...   
183087545    0.000983
188574944    0.000983
140199494    0.000983
120975314    0.000983
175429310    0.000983
Name: proportion, Length: 71518, dtype: float64

Column: race
race
Caucasian          76.486788
AfricanAmerican    19.307891
Hispanic            2.047380
Other               1.513674
Asian               0.644266
Name: proportion, dtype: float64

Column: gender
gender
Female             53.758623
Male               46.238429
Unknown/Invalid     0.002948
Name: proportion, dtype: float64

Column: ag

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      99493 non-null   str  
 3   gender                    101766 non-null  str  
 4   age                       101766 non-null  str  
 5   weight                    3197 non-null    str  
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                61510 non-null   str  
 11  medical_specialty         51817 non-null   str  
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           10176

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO


In [16]:
df.to_csv("../data/processed/patient_encounters_2023.csv")